### PR TITLE
morphia=0.111, mongo-java-driver=2.13.1 migration

### PR DESCRIPTION
**Pull request by ugurlu**
Unit tests are passing.

### CODE REVIEW

**Comment by shoon** [comment]
Passed our environment checks

**Comment by tonybaroneee** [comment]
Also verified working in production for my app. Thank you so much!

Would love to see this merged soon so I can get rid of the PR's .jar as a local dependency.

**Comment by tonybaroneee** [comment]
Any chance you're going to cut 1.5.0 soon? Thanks.

**Comment by greenlaw110** [comment]
It's uploaded to http://greenlaw110.com/play/repo/play-morphia-1.5.0b.zip

**Pull request merged**
